# before compiling -> sudo pkg install portaudio gmake aarch64-binutils flac libmad faad2 mpg123 libvorbis

CPPFLAGS = -I/usr/local/include -I/usr/local/include/portaudio2
CFLAGS  = -Wall -fPIC -O3 -march=armv8-a+crc -DDSD
LDFLAGS = -L/usr/local/lib -L/usr/local/lib/portaudio2 -lportaudio -lpthread -lm
EXECUTABLE = squeezelite-raspbsd_ARM64

include Makefile
